### ISSUE TITLE
Question About Move Function

### ISSUE THREAD

**Issue by enrutador** [kevinsteves/pan-python#18]
Incredible work, many congratulations¡¡¡
I am testing with the API and I have a question at the moment of moving a rule in a certain position.

To perform this action I perform the following command:

> 

panxapi.py -h 10.0.0.1 -l admin:PASSWORD --move "/config/devices/entry/vsys/entry/rulebase/security/rules/entry[@name='rule-test']" before "/config/devices/entry/vsys/entry/rulebase/security/rules/entry[@name='rule-test1']"

> 

But it gives me the following error:

Invalid where: "/config/devices/entry/vsys/entry/rulebase/security/rules/entry[@name='rule-test1']"

move: error [code="7"]: "no target specified in move"

I have tried several combinations but it gives me error can you show me some examples?

Thanks and Regards

**Comment by kevinsteves** [comment]
move can be confusing, but it is specified as:

`--move where --dst relative_node_name src_xpath`

so I think you want:

`--move before --dst rule-test1 "/config/devices/entry/vsys/entry/rulebase/security/rules/entry[@name='rule-test']"`

To move rule-test before rule-test1.

Let me know if that works.

**Comment by enrutador** [comment]
Great Kevin ¡¡¡¡
Thank you very much for the clarification, your annotation works¡¡¡¡ I am applying the same to the concept for `--Clone`  function 

`panxapi.py -h 10.0.0.1 -l admin:password  --clone --src "/config/devices/entry/vsys/entry/rulebase/security/rules/entry[@name='rule-test']" --dst "rule-test2"`

But in this case  the error output is 

`clone: error [code="6"]: "cannot clone object here"`


A lot of Thanks for the help

**Comment by kevinsteves** [comment]
clone can be confusing also, you want something like:

`--clone --dst rule1-clone --src "/config/devices/entry/vsys/entry/rulebase/security/rules/entry[@name='rule1']" "/config/devices/entry/vsys/entry/rulebase/security/rules"`

to clone rule1 to rule1-clone.

**Comment by enrutador** [comment]
Great Kevin¡¡¡¡¡
Your annotation works ¡¡¡Thanks for making this world better with your work
Thank you very much

**Comment by kevinsteves** [comment]
I will work to add/update panxapi.py examples.
