### ISSUE TITLE
Delete Service Object from a rule

### ISSUE THREAD

**Issue by enrutador** [kevinsteves/pan-python#20]
Hi Kevin
I have a problem with how to delete a service defined in a Rule:

With the following command I am able to create the service previously defined in an existing rule:

```
#panxapi.py -h 10.0.0.1 -l admin:admin -j -S '<service><member>tcp_10007</member></service>' "/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='"VIRTUAL"']/pre-rulebase/security/rules/entry[@name='rule-test']"

set: success [code="20"]: "command succeeded"
{
  "response": {
    "code": "20",
    "msg": "command succeeded",
    "status": "success"
  }
}

```
But when I want to erase, I get the following error:

```
#panxapi.py  -h 10.0.0.1 -l admin:admin -j -d '<service><member>tcp_10007</member></service>' "/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='"VIRTUAL"']/pre-rulebase/security/rules/entry[@name='rule-test']"

Extra options after xpath: ["/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='VIRTUAL']/pre-rulebase/security/rules/entry[@name='rule-test']"]

delete: unauth [code="16"]: "Unauthorized request"
{
  "response": {
    "code": "16",
    "msg": {
      "line": "Unauthorized request"
    },
    "status": "unauth"
  }
}

```

Am I using the commands correctly? , Or should use another methodology to delete the services.
Greetings and thanks

**Comment by kevinsteves** [comment]
Notice the "Extra options after xpath" warning.  -d
(type=config&action=delete) does not take an XML document argument.
delete only uses the XPath of the node.

There is some lab material that covers this and other topics here:

    http://api-lab.paloaltonetworks.com/module-2.html

This discusses how you can determine the XPath to use with 'debug cli
on'.

**Comment by enrutador** [comment]
Good morning, Kevin.
I am launching the following commands, marking the object node that I want to delete, but it does not delete the service of the policy.
```

panxapi.py  -h 10.0.0.1 -l admin:admin -j  -d "/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='"VIRTUAL"']/pre-rulebase/security/rules/entry[@name='rule-test']/service/member/entry[@name='tcp-10001']"

delete: success [code="7"]: "Object doesn't exist"
{
  "response": {
    "code": "7",
    "msg": "Object doesn't exist",
    "status": "success"
  }
}

```
In my case the system is a panorama, when i put on debug mode i only see this:

```
XML Api Request
 <request cmd='delete' obj="/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='VIRTUAL']/pre-rulebase/security/rules/entry[@name='rule-test']/service/member/entry[@name='tcp-10001']" cookie='1498255326095045' client='xmlapi'></request>

[2017/08/25 11:05:25] user=1498255326095045
XML Api Request End
```
The problem is to determine the end of the service tree, I have tested with the following combinations:

```
/service/member/entry[@name='tcp-10001']"
/service/member/tcp-10001"
/service/tcp-10001"

```
But always with the same error

```
delete: success [code="7"]: "Object doesn't exist"
{
  "response": {
    "code": "7",
    "msg": "Object doesn't exist",
    "status": "success"
  }
}

```
If I throw the command so that, if it is able to delete all the services:

```
panxapi.py  -h 10.0.0.1 -l admin:admin -j  -d "/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='"VIRTUAL"']/pre-rulebase/security/rules/entry[@name='rule-test']/service"
delete: success [code="20"]: "command succeeded"
{
  "response": {
    "code": "20",
    "msg": "command succeeded",
    "status": "success"
  }
}
```
Thanks for your help

**Comment by kevinsteves** [comment]
I can't explain how you got the debug output you posted, however I expect you to see something like this which uses the text() function to determine the node:

<request cmd="delete" obj="/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='chandler']/pre-rulebase/security/rules/entry[@name='test-rule']/service/member[text()='service-http']" cookie="5704782760012922"></request>

**Comment by enrutador** [comment]
Hi Kevin ¡¡¡¡
A lot of thanks with your sample now i can understand . I do the debug on the panorama with this url:

https://panorama-ip/debug

In this url i can capture de message of the device

Thanks ¡¡
