### ISSUE TITLE
Connection reset by peer error

### ISSUE THREAD

**Issue by irom77** [kevinsteves/pan-python#22]
Getting **Connection reset by peer** error below, PAN 8.0.5, please advice

```
panxapi.py -h 10.0.0.85 -l admin:jenkins -k
keygen: "URLError: reason: [Errno 54] Connection reset by peer"
```

**Comment by import-au** [comment]
I'm having the same issue.

**Comment by kevinsteves** [comment]
yes, this is the same as:
https://github.com/kevinsteves/pan-python/issues/15

you can change the PAN-OS config as described if you cannot update your openssl.

**Comment by kevinsteves** [comment]
result of documented change in 8.0.
