### ISSUE TITLE
session id

### ISSUE THREAD

**Issue by ngssupport** [kevinsteves/pan-python#24]
panxapi.py  -t TAG -jo 'show session id ID'

ends with error

op: error [code="17"]: "  is unexpected"
{
  "response": {
    "code": "17",
    "msg": {
      "line": "  is unexpected"
    },
    "status": "error"
  }
}

**Comment by kevinsteves** [comment]
You need to use -X if you do not provide the XML op command document.

`$ panxapi.py -t pa-220 -Xjo 'show session id "10"'

op: success
{
  "response": {
    "result": {
      "app-insufficient": "False",
      "application": "facebook-base",
`

**Comment by kevinsteves** [comment]
closing as solved.
