### ISSUE TITLE
commit reports success, even though job failed

### ISSUE THREAD

**Issue by cjreyn** [kevinsteves/pan-python#25]
Commiting some candidate configuration to a single Palo Alto using panxapi.py reports the commit job was successful, even though the message reports it failed:

reynolds@admin-1:~/wc/pan-python-0.12.0/bin$ ./panxapi.py -t xapilab -C '' --sync
commit: success: "vsys1
    Error: vsys1 decryption: forward decrypt trust cert is not configured
    Error: Failed to parse decryption policy
(Module: device)
Commit failed"

I expect the commit to fail, but the panxapi.py script should report this. It doesn't seem to raise a pan.xapi.PanXapiError exception.

**Comment by kevinsteves** [comment]
Unfortunately, this is how the interface was implemented, and changing
it now is unlikely.  pan.xapi just reports the return status of
"success".  I believe the pandevice SDK, built over pan.xapi, will try
to determine commit error/fail cases by examining the response message.
