### ISSUE TITLE
pan.xapi user_id : dynamic objects update via panorama failed "Missing vsys"

### ISSUE THREAD

**Issue by nergalex** [kevinsteves/pan-python#27]
Hello,

An error is encountered when an dynamic objects update is done via PANORAMA to a specific TARGET, but it works when it's done directly to a PAN FW.

Error via PANORAMA :f. pan-python_dag_update-via_panorama
[pan-python_dag_update-via_panorama.log](https://github.com/kevinsteves/pan-python/files/2280312/pan-python_dag_update-via_panorama.log)

Success directly : cf. pan-python_dag_update-direct_to_pan_fw
[pan-python_dag_update-direct_to_pan_fw.log](https://github.com/kevinsteves/pan-python/files/2280314/pan-python_dag_update-direct_to_pan_fw.log)

Regards,
Alexis

**Comment by nergalex** [comment]
To complete :
- PANORAMA OS : 8.0.2
- PAN FW : 8.0.9

**Comment by kevinsteves** [comment]
closing as fixed in PAN-77290

**Comment by nergalex** [comment]
It's OK with PANORAMA 8.0.9
Sorry for the delay.
Thank you
