### ISSUE TITLE
PANOS 9.x issue

### ISSUE THREAD

**Issue by kimthostrup** [kevinsteves/pan-python#32]
Hi,

When testing the the following towards 9.x, it does not return any content.
xapi.op(cmd='show system resources', cmd_xml=True)

I suspect that the reason for this is that the output of the top command has changed from: 8.x
----snip----
top - 10:29:54 up  1:14,  2 users,  load average: 0.56, 0.78, 1.00
Tasks: 132 total,   2 running, 130 sleeping,   0 stopped,   0 zombie
Cpu(s): 11.6%us,  6.0%sy,  0.4%ni, 81.8%id,  0.1%wa,  0.0%hi,  0.2%si,  0.0%st
Mem:   4561772k total,  4150224k used,   411548k free,    46492k buffers
Swap:        0k total,        0k used,        0k free,  2245248k cached
----snip----

to the following in 9.x
----snip----
top - 17:27:58 up 3 days,  9:24,  1 user,  load average: 2.18, 2.15, 2.20
Tasks: 135 total,   3 running, 132 sleeping,   0 stopped,   0 zombie
%Cpu(s): 52.5 us,  1.2 sy,  0.7 ni, 45.6 id,  0.1 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  4119652 total,   272224 free,  1901384 used,  1946044 buff/cache
KiB Swap:     1972 total,     1972 free,        0 used.  1740796 avail Mem
----snip----

/Kim

**Comment by kevinsteves** [comment]
`$ panxapi.py -t vm-50-1 -Xxo 'show system resources'`

does return content/command output in response for me on 9.0.2.  This performs the
same method call you reference.

**Comment by kevinsteves** [comment]
can't dup.
