### ISSUE TITLE
API Key generation - Password Regex not matching

### ISSUE THREAD

**Issue by Sai-Tumuluri** [kevinsteves/pan-python#37]
```
c:\Users\stumuluri>panxapi.py --version
pan-python 0.15.0

```
```
c:\Users\stumuluri\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\pan>panxapi.py -t '' -h 10.46.165.136 -l backup -k
C:\Users\stumuluri\AppData\Local\Programs\Python\Python37-32\Scripts\..\lib\getpass.py:100: GetPassWarning: Can not control echo on the terminal.
  return fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
Password: cseteam
pan.xapi.PanXapi: tag must match regexp "^[\w-]+$"
```
```
c:\Users\stumuluri\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\pan>panxapi.py -t '' -h 10.46.165.136 -l backup:cseteam -k
pan.xapi.PanXapi: tag must match regexp "^[\w-]+$"
```

**Comment by kevinsteves** [comment]
Can you run the 2nd example with -DDD so we can see what 'tag' in options is set to?

**Comment by Sai-Tumuluri** [comment]
G:\My Drive\Coding\Prisma_access_deployer>panxapi.py -DDD -t '' -h 10.46.165.136 -l backup:cseteam -k
{   'ad_hoc': None,
    'api_key': None,
    'api_password': 'cseteam',
    'api_username': 'backup',
    'cafile': None,
    'capath': None,
    'clone': False,
    'cmd': None,
    'cmd_xml': False,
    'commit': False,
    'commit_all': False,
    'debug': 3,
    'delete': False,
    'dst': None,
    'dynamic-update': False,
    'edit': False,
    'element': None,
    'export': None,
    'filter': None,
    'force': False,
    'get': False,
    'group': None,
    'hostname': '10.46.165.136',
    'interval': None,
    'job_timeout': None,
    'keygen': True,
    'log': None,
    'merge': False,
    'modify': False,
    'move': None,
    'name': None,
    'nlogs': None,
    'op': None,
    'override': False,
    'partial': [],
    'pcap_listing': False,
    'pcapid': None,
    'port': None,
    'print_json': False,
    'print_python': False,
    'print_result': False,
    'print_text': False,
    'print_xml': False,
    'recursive': False,
    'rename': False,
    'report': None,
    'serial': None,
    'set': False,
    'show': False,
    'skip': None,
    'src': None,
    'stime': None,
    'sync': False,
    'tag': "''",
    'timeout': None,
    'use_get': False,
    'use_http': False,
    'validate': False,
    'vsys': [],
    'xpath': None}
Python version: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]
xml.etree.ElementTree version: 1.3.0
ssl: OpenSSL 1.1.1c  28 May 2019
pan-python version: 0.15.0
pan.xapi.PanXapi: tag must match regexp "^[\w-]+$"

**Comment by kevinsteves** [comment]
the issue is 'tag': "''"

If you use -t "" what is result?  we expect a null string for this case.

**Comment by Sai-Tumuluri** [comment]
I tried null string using single quotes. I will try with double quotes

**Comment by kevinsteves** [comment]
does this still occur with -t "" ?

**Comment by kevinsteves** [comment]
please reopen if double quotes doesn't work.
