### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by nstr10** [kevinsteves/pan-python#38]
Using Python 3.7.3 and Ubuntu 18.04, everything seems to work as described in the docs.

Using Python 3.7.3 and Windows 7, not so much:
```sh
~> panxapi.py --help
pan.xapi.PanXapi: hostname argument required
~> panxapi.py -h 10.X.X.X -l apitest:p@ssw0rd -k
pan.xapi.PanXapi: hostname argument required
```

Am I doing something wrong?

**Comment by nstr10** [comment]
Ended up just importing the library and using it that way. The lack of documentation for any usage other than commandline was a major roadblock but I ended up figuring out the basics by looking at other people's code who have used this library.

**Comment by kevinsteves** [comment]
I don't use Windows but a number of people use pan-python on it.

I'm told you need to use something like ``python3.exe panxapi.py --help``

**Comment by kevinsteves** [comment]
The module documentation is at:

https://github.com/kevinsteves/pan-python/blob/master/doc/pan.xapi.rst

**Comment by nstr10** [comment]
Wow not sure how I overlooked that documentation - still no idea why commandline isn't working for me, but if it's working for everyone else then it must be a me problem. :)
