### ISSUE TITLE
Document Filter Syntax

### ISSUE THREAD

**Issue by nstr10** [kevinsteves/pan-python#39]
Can't for the life of me figure out how to pass a filter to a log query. Hoping to avoid picking apart the source to figure it out...

**Comment by kevinsteves** [comment]
It's documented here (same as query in UI Monitor tab):

https://github.com/kevinsteves/pan-python/blob/master/doc/pan.xapi.rst#logself-log_typenone-nlogsnone-skipnone-filternone-intervalnone-timeoutnone

**Comment by nstr10** [comment]
Thanks! Turns out I wasn't formatting my timestamps properly.
