### ISSUE TITLE
Getting 502 randomly on commit to panorama

### ISSUE THREAD

**Issue by jepify** [kevinsteves/pan-python#43]
@kevinsteves, I am randomly (i think) getting this error
`raise PanXapiError('commit %s: %s' % (cmd, msg))
pan.xapi.PanXapiError: commit show jobs id "161421": URLError: code: 502 reason: Bad Gateway`
while commiting via the XAPI. 

I am making the request via 
`xapi.commit(cmd=commit, sync=True, interval=1.0)`
And have tried with default interval also. 

The error seems to happen when making many consecutive calls to panorama

**Comment by kevinsteves** [comment]
What is the PAN-OS version?  It is failing on the "show jobs id NN" which is done when sync=True to determine when the commit job is complete.

You can take a look at ms.log and php.debug.log (`tail mp-log xxx`) for some clues.

But I would suggest to log a support case.

**Comment by jepify** [comment]
We are running version 9.1. 
I may have found the problem. It seems to happen when having multiple instances of the xapi object, which concurrently queries Panorama.

**Comment by kevinsteves** [comment]
closing.  please re-open if problem is not resolved.
