### ISSUE TITLE
how can i add Address in Used Address Group?

### ISSUE THREAD

**Issue by MisterDooonut** [kevinsteves/pan-python#45]
i use xapi.edit, but it just override.

how can i Edit Address Group? not Override

**Comment by kevinsteves** [comment]
http://api-lab.paloaltonetworks.com/set-edit-object.html#lab-6

**Comment by MisterDooonut** [comment]
> http://api-lab.paloaltonetworks.com/set-edit-object.html#lab-6

Thanks for your reply!, i use csv file(name, ip column) and pan-os sdk


**if __name__ == '__main__':
    data = pd.read_csv("address.csv")
    data_len = len(data)
    data_name = data['name']
    data_ip = data['ip']

    fw = panos.firewall.Firewall(HOSTNAME, USERNAME, PASSWORD)

    for i in range(data_len):
        fw.add(panos.objects.AddressObject("%s" % data_name[i], "%s" % data_ip[i])).create()
    fw.add(panos.objects.AddressGroup("Test_Address_Group",data_name)).create()

    fw.commit()**


it looks like newb, but it works! haha
thank you!!
