### ISSUE TITLE
Support for PANOS 10

### ISSUE THREAD

**Issue by dhalperi** [kevinsteves/pan-python#48]
https://github.com/kevinsteves/pan-python/blob/master/lib/pan/config.py#L584-L609

This code specifies which xpaths are relevant for different versions of PANOS, but 10.0 and 10.1 are both not in the list. As a result, it seems to fall back to 4.1. Looks like we need to add support for these new versions to get correct behavior.

**Comment by dhalperi** [comment]
How this affected us: we download `show` output from panorama and then use `panconf` to convert it into `set` format. This second step dropped important data from the XML.

**Comment by kevinsteves** [comment]
Should be addressed in master branch.  Please verify.  Thanks.

**Comment by dhalperi** [comment]
User report:

> I installed pan-python from the latest commit and it works without modification now!

Thanks @kevinsteves !

Obviously a pypi release would be helpful, but I'm sure you all have lots going on.
