### ISSUE TITLE
Cannot install through pip

### ISSUE THREAD

**Issue by ajaymills** [kevinsteves/pan-python#5]
Using pip3.4 as of writing I cannot successfully install pan. Looks like a missing file. Output:

Downloading/unpacking pan
  Downloading pan-0.1.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/pan/setup.py) egg_info for package pan
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/pan/setup.py", line 1, in <module>
        import distribute_setup
    ImportError: No module named 'distribute_setup'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/pan/setup.py", line 1, in <module>

    import distribute_setup

ImportError: No module named 'distribute_setup'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/pan
Storing debug log for failure in /root/.pip/pip.log

**Comment by kevinsteves** [comment]
pan-0.1.1.tar.gz isn't the pan-python package.

**Comment by ajaymills** [comment]
My bad, that's right-- should have been "pan-python". That one installed correctly.
